# 参考 https://docs.readthedocs.com/platform/stable/intro/zensical.html

# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    install:
      - pip install -r docs/requirements.txt
#      - pip install zensical
    build:
      html:
        - zensical build
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
