# mkdocs.yml
# mkdocs 主配置文件
# https://squidfunk.github.io/mkdocs-material/getting-started/

site_name: "Kevin's Wiki"

# 手动设置导航栏内容
#nav:
#  - index.md
#  - Blog:
#    - blog/index.md


theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: assets/favicon.png
  # 不使用 google font
  font: false

  features:
    # instant loading
    - navigation.instant
    # 导航栏
    - navigation.tabs
    # 固定导航栏
    - navigation.tabs.sticky
    # 搜索关键字高亮
    - search.highlight
    # 底部导航箭头
    - navigation.footer
    - navigation.top

  # 根据系统设置切换 light、dark 模式
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


plugins:
  - search
  - blog
  # 用于显示文档精确元信息的 MkDocs 插件，如创建时间、最后更新时间、作者、电子邮件等
  - document-dates:
      position: top            # 显示位置：top（标题后） bottom（文档末尾）
      type: date               # 时间类型：date datetime timeago，默认：date
      exclude:                 # 排除文件列表
        - temp.md              # 排除指定文件
        - drafts/*             # 排除 drafts 目录下所有文件，包括子目录
      locale: zh               # 本地化语言：en zh zh_TW es fr de ar ja ko ru，默认：en
      date_format: '%Y-%m-%d'  # 日期格式化字符串，例如：%Y年%m月%d日、%b %d, %Y
      time_format: '%H:%M:%S'  # 时间格式化字符串（仅在 type=datetime 时有效）
      show_author: false        # 是否显示作者信息，默认：true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kisa747


# 加载额外的 css 样式
extra_css:
  - assets/extra.css


# 是否显示 Made with Material for MkDocs
#generator: false
# 版权声明
copyright: Copyright &copy; 2025 - 2025 kisa747
# 显示仓库地址
repo_url: https://github.com/kisa747
edit_uri: ""

markdown_extensions:
  # 注释标题支持
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  #  - mkautodoc

  # 代码标题支持
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # 表格支持
  - tables

  # 公式支持，参考：https://squidfunk.github.io/mkdocs-material/reference/math/
  - pymdownx.arithmatex:
      generic: true

  # 扩展语法支持
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript:
  # 公式支持，参考：https://squidfunk.github.io/mkdocs-material/reference/math/
  - assets/js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
